CREATE DATABASE IF NOT EXISTS ALX_prodev

CREATE TABLE user_data(
    user_id INT PRIMARY KEY UUID INDEXED,
    name VARCHAR(130) NOT NULL,
    email VARCHAR(130) NOT NULL,
    age DECIMAL NOT NULL
);
